# Generated by Django 5.0.1 on 2024-02-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='astrological_sign',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
