# Generated by Django 5.0.1 on 2024-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile_astrological_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
