# Generated by Django 5.0.1 on 2024-03-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile_first_profile_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
